// My DID identity, without the page: create an Ed25519 did:key, seal it in an encrypted backup,
// open that backup again, prepare and sign a first message, and check what Technocore stored.
// Plain JavaScript over Web Crypto, so the Node tests run it as is. Nothing here touches the network
// or any storage: the caller keeps the identity in memory and decides what, if anything, is sent.
//
// Formats (documented in ROOM_CENSUS_UX_SPEC.md on the planning branch):
// - key: Ed25519, held as a PKCS#8 DER private key (48 bytes: fixed 16-byte prefix + 32-byte seed);
// - DID: "did:key:z" + base58btc(0xed 0x01 + 32-byte public key), 56 characters;
// - backup "room-census-did-backup/1": the PKCS#8 bytes sealed with AES-256-GCM under a key derived
//   from the password with PBKDF2-HMAC-SHA256 (600,000 iterations, 16-byte random salt), 12-byte
//   random IV; every header field is bound as additional data, so any change makes opening fail;
// - message: Ed25519 over the UTF-8 bytes of "<room>|<nonce>|<text>", text after Technocore's
//   single-line sweep, signature base64url without padding (86 characters).

import { publicKey } from "./did-core.mjs";

export const BACKUP_SCHEMA = "room-census-did-backup/1";
export const PROOF_SCHEMA = "room-census-did-post-proof/1";
export const ITERATIONS = 600000;
export const MIN_PASSWORD = 12;
export const MAX_TEXT = 4096;
// Where a first introduction is proposed. The room-census room stays for signed censuses and its
// track commands, so introductions go to a room of their own. It does not exist yet: until Ben
// creates it and `ready` becomes true, the page proposes another existing room instead and never
// writes to it (a first write would create the room).
export const COMMUNITY = { room: "room-census-community", ready: false };
// rooms a message may never go to, whatever the reader types
export const RESERVED = ["room-census", "events"];
const PKCS8_PREFIX = Uint8Array.from([0x30, 0x2e, 0x02, 0x01, 0x00, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x04, 0x22, 0x04, 0x20]);
const B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
const DID_RE = /^did:key:z6Mk[1-9A-HJ-NP-Za-km-z]{44}$/;

/** A backup or identity problem. `code` is safe to show; no message ever carries key material. */
export class WalletError extends Error {
  constructor(code, message) {
    super(message);
    this.code = code;
  }
}

const b64url = (bytes) => btoa(String.fromCharCode(...bytes)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
function unb64url(text, length) {
  if (typeof text !== "string" || !/^[A-Za-z0-9_-]*$/.test(text)) return null;
  try {
    const bin = atob(text.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - (text.length % 4)) % 4));
    const out = Uint8Array.from(bin, (c) => c.charCodeAt(0));
    return length === undefined || out.length === length ? out : null;
  } catch {
    return null;
  }
}

function base58(bytes) {
  const digits = [0];
  for (const byte of bytes) {
    let carry = byte;
    for (let i = 0; i < digits.length; i++) {
      carry += digits[i] << 8;
      digits[i] = carry % 58;
      carry = (carry / 58) | 0;
    }
    while (carry > 0) { digits.push(carry % 58); carry = (carry / 58) | 0; }
  }
  let out = "";
  for (const byte of bytes) { if (byte !== 0) break; out += "1"; }
  for (let i = digits.length - 1; i >= 0; i--) out += B58[digits[i]];
  return out;
}

/** The did:key of a 32-byte Ed25519 public key. */
export const didOf = (raw) => `did:key:z${base58(Uint8Array.from([0xed, 0x01, ...raw]))}`;

const samePrefix = (pkcs8) => pkcs8.length === 48 && PKCS8_PREFIX.every((b, i) => pkcs8[i] === b);

/**
 * Imports a PKCS#8 Ed25519 key as a non-extractable key and proves it belongs to `did`: it signs a
 * challenge that the DID's public key must verify. The key is never exported in any other form.
 */
async function keyFor(subtle, pkcs8, did) {
  if (!samePrefix(pkcs8)) throw new WalletError("mismatch", "The key in this backup does not match its DID.");
  const privateKey = await subtle.importKey("pkcs8", pkcs8, { name: "Ed25519" }, false, ["sign"]);
  const challenge = new TextEncoder().encode(`room-census-key-check|${did}`);
  const pub = await subtle.importKey("raw", publicKey(did), { name: "Ed25519" }, false, ["verify"]);
  const sig = await subtle.sign({ name: "Ed25519" }, privateKey, challenge);
  if (!(await subtle.verify({ name: "Ed25519" }, pub, sig, challenge))) {
    throw new WalletError("mismatch", "The key in this backup does not match its DID.");
  }
  return privateKey;
}

/**
 * A new identity, generated by the browser's own secure random source. Returns {did, privateKey, pkcs8}:
 * `pkcs8` is needed once, to seal the backup, and should be wiped with `forget` right after.
 */
export async function createIdentity(subtle) {
  const pair = await subtle.generateKey({ name: "Ed25519" }, true, ["sign", "verify"]);
  const pkcs8 = new Uint8Array(await subtle.exportKey("pkcs8", pair.privateKey));
  const did = didOf(new Uint8Array(await subtle.exportKey("raw", pair.publicKey)));
  const privateKey = await keyFor(subtle, pkcs8, did);
  return { did, privateKey, pkcs8 };
}

/** Overwrites secret bytes held by the page once they are no longer needed. */
export const forget = (bytes) => bytes?.fill(0);

/** Why a password cannot seal a backup, or null. */
export function passwordProblem(password, confirm) {
  if (typeof password !== "string" || [...password].length < MIN_PASSWORD) return `Use at least ${MIN_PASSWORD} characters.`;
  if (password !== confirm) return "The two passwords are not the same.";
  return null;
}

// every header field, in a fixed order: this string is authenticated with the ciphertext
export const backupHeader = (b) => JSON.stringify([b.schema, b.did, b.created_at, b.kdf.name, b.kdf.hash, b.kdf.iterations, b.kdf.salt, b.cipher.name, b.cipher.iv]);

async function aesKey(subtle, password, salt, iterations, usage) {
  const base = await subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveKey"]);
  return subtle.deriveKey({ name: "PBKDF2", hash: "SHA-256", salt, iterations }, base, { name: "AES-GCM", length: 256 }, false, [usage]);
}

/** Seals the PKCS#8 key into a backup object (JSON-ready). `random(n)` gives n secure random bytes. */
export async function sealBackup(subtle, random, { did, pkcs8 }, password, createdAt = new Date().toISOString()) {
  if (!samePrefix(pkcs8)) throw new WalletError("mismatch", "There is no key to back up.");
  const salt = random(16);
  const iv = random(12);
  const backup = {
    schema: BACKUP_SCHEMA, did, created_at: createdAt,
    kdf: { name: "PBKDF2", hash: "SHA-256", iterations: ITERATIONS, salt: b64url(salt) },
    cipher: { name: "AES-GCM", iv: b64url(iv) },
  };
  const key = await aesKey(subtle, password, salt, ITERATIONS, "encrypt");
  const sealed = await subtle.encrypt({ name: "AES-GCM", iv, additionalData: new TextEncoder().encode(backupHeader(backup)), tagLength: 128 }, key, pkcs8);
  return { ...backup, ciphertext: b64url(new Uint8Array(sealed)) };
}

const KEYS = ["cipher", "ciphertext", "created_at", "did", "kdf", "schema"];
const exactKeys = (o, keys) => o && typeof o === "object" && !Array.isArray(o) && Object.keys(o).sort().join() === keys.join();

/**
 * Opens a backup file's text with its password and returns {did, privateKey}. Every failure is a
 * WalletError: "format", "version", "password" (wrong password or changed file) or "mismatch".
 */
export async function openBackup(subtle, text, password) {
  let b;
  try {
    b = JSON.parse(text);
  } catch {
    throw new WalletError("format", "This is not a Room Census DID backup file.");
  }
  if (b && typeof b === "object" && typeof b.schema === "string" && b.schema.startsWith("room-census-did-backup/") && b.schema !== BACKUP_SCHEMA) {
    throw new WalletError("version", "This backup comes from a newer version of this page, which this one cannot open.");
  }
  const salt = unb64url(b?.kdf?.salt, 16);
  const iv = unb64url(b?.cipher?.iv, 12);
  const sealed = unb64url(b?.ciphertext, 64);
  if (!exactKeys(b, KEYS) || b.schema !== BACKUP_SCHEMA || typeof b.did !== "string" || !DID_RE.test(b.did) || !publicKey(b.did)
      || typeof b.created_at !== "string" || !exactKeys(b.kdf, ["hash", "iterations", "name", "salt"]) || b.kdf.name !== "PBKDF2"
      || b.kdf.hash !== "SHA-256" || b.kdf.iterations !== ITERATIONS || !exactKeys(b.cipher, ["iv", "name"]) || b.cipher.name !== "AES-GCM"
      || !salt || !iv || !sealed) {
    throw new WalletError("format", "This is not a Room Census DID backup file, or it is damaged.");
  }
  if (typeof password !== "string" || password === "") throw new WalletError("password", "Enter the password of this backup.");
  let pkcs8;
  try {
    const key = await aesKey(subtle, password, salt, b.kdf.iterations, "decrypt");
    pkcs8 = new Uint8Array(await subtle.decrypt({ name: "AES-GCM", iv, additionalData: new TextEncoder().encode(backupHeader(b)), tagLength: 128 }, key, sealed));
  } catch {
    throw new WalletError("password", "Wrong password, or the file was changed.");
  }
  try {
    return { did: b.did, privateKey: await keyFor(subtle, pkcs8, b.did) };
  } finally {
    forget(pkcs8);
  }
}

/** Technocore's single-line sweep: controls, format, surrogate, private-use and line/paragraph separators become spaces, ends trimmed. */
export const sweep = (text) => String(text).replace(/[\p{Cc}\p{Cf}\p{Cs}\p{Co}\p{Zl}\p{Zp}]/gu, " ").trim();

/** The introduction proposed right after a DID is created. Both parts must be replaced. */
export const INTRODUCTION = "I created my Technocore identity with Room Census. I am interested in [topic], and I plan to contribute by [contribution].";

/** Editable starters for a message. Never sent as they are: every [field] must be replaced. */
export const STARTERS = [
  { id: "project", label: "Introduce a project", text: "I am building [project] to [useful purpose]. I would appreciate feedback on [specific question]." },
  { id: "learning", label: "Share a learning goal", text: "I am exploring Technocore to learn more about [topic]. My next concrete step is [action]." },
  { id: "test", label: "Test the new identity", text: "I am testing my new signed Technocore identity. I plan to use it for [real project or contribution]." },
  { id: "collaborators", label: "Find collaborators", text: "I am looking for people interested in [topic]. I can contribute [specific skill, data or project]." },
];

/** Why a message cannot be signed yet, or null. `allowed` is the list of rooms the page carries. */
export function messageProblem(room, text, allowed) {
  if (!Array.isArray(allowed) || !allowed.includes(room)) return "Choose a room from the list.";
  if (RESERVED.includes(room)) return "This room is reserved for signed censuses.";
  const swept = sweep(text);
  if (swept === "") return "Write your message.";
  if (/\[[^\]]*\]/.test(swept)) return "Replace every part in [brackets] with your own words.";
  if ([...swept].length > MAX_TEXT) return `Keep it under ${MAX_TEXT} characters.`;
  return null;
}

/** Signs the exact Technocore payload and checks the signature before anything else sees it. */
export async function signMessage(subtle, identity, room, nonce, text) {
  const swept = sweep(text);
  const data = new TextEncoder().encode(`${room}|${nonce}|${swept}`);
  const sig = b64url(new Uint8Array(await subtle.sign({ name: "Ed25519" }, identity.privateKey, data)));
  const pub = await subtle.importKey("raw", publicKey(identity.did), { name: "Ed25519" }, false, ["verify"]);
  const back = unb64url(sig, 64);
  if (sig.length !== 86 || !back || !(await subtle.verify({ name: "Ed25519" }, pub, back, data))) {
    throw new WalletError("signature", "The message could not be signed correctly; nothing was sent.");
  }
  return { room, nonce, text: swept, did: identity.did, sig };
}

/** A nonce above any this key could have spent: the millisecond clock, at least 13 digits. */
export const nextNonce = (now = Date.now()) => String(Math.max(1, Math.floor(now)));

/** A dated proof of one publication attempt, with the complete server reply when there is one. */
export function proofOf(signed, outcome, reply, stored, at = new Date().toISOString()) {
  return {
    schema: PROOF_SCHEMA,
    outcome,
    recorded_at: at,
    room: signed.room,
    did: signed.did,
    nonce: signed.nonce,
    text: signed.text,
    sig: signed.sig,
    signed_payload: `${signed.room}|${signed.nonce}|${signed.text}`,
    seq: stored?.seq ?? null,
    ts: stored?.ts ?? null,
    server_reply: reply ?? null,
    note: "seq and ts are assigned by technocore.chat and are not covered by the signature.",
  };
}
